language: php

php:
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
# setup application:
script:
  - phantomjs --webdriver=4444 > /dev/null 2>&1 &
  - |
    cd tests
    cd ../web
    php -S localhost:8080 > /dev/null 2>&1 &
    cd ../tests
    ../vendor/bin/codecept run unit
    ../vendor/bin/codecept run acceptance